analyzer:
  errors:
    unused_import: warning
    dead_code: warning
    unnecessary_getters_setters: warning
    unnecessary_new: warning
    unnecessary_this: warning

linter:
  rules:
    prefer_single_quotes: true
    always_specify_types: true
    avoid_print: true
    prefer_const_constructors: true
    prefer_final_fields: true
    type_annotate_public_apis: true

include: package:flutter/analysis_options.yaml